### ISSUE TITLE
*_ids not permitted (e.g., 'customer_ids')

### ISSUE THREAD

**Issue by jlee42** [colinyoung/cancan_strong_parameters#6]
When adding the param `:customer_ids` (for checkboxes), this gem does not support the permission of the attribute properly.

`permit_params :username, :customer_ids => []` nor `permit_params :username, :customer_ids` allows the `:customer_ids` attribute through. The error message `Unpermitted parameters: customer_ids` is returned.

See: http://stackoverflow.com/questions/15376148/cannot-permit-parameters

`permit_all_params` works, though.

**Comment by djhopper01** [comment]
I'm seeing this as well. I believe it works correctly without this gem.

**Comment by colinyoung** [comment]
Thanks, @jlee42!
