### ISSUE TITLE
Gem Name Misleading! It's Not Just for CanCan

### ISSUE THREAD

**Issue by joshhepworth** [colinyoung/cancan_strong_parameters#7]
It's potentially worth noting that this project isn't actually specific to CanCan. This will work well for any auto-resource-loading gem. For example, with ActiveAdmin:

``` ruby
ActiveAdmin.register Member do
  controller do
    permit_params :project_id, :name, :email
  end
end
```

It might be worth renaming the gem!

**Comment by colinyoung** [comment]
Thanks for the point! Renaming a gem seems like it might be too hard, but I'll think about it - and I'll also update the readme to mention your point. Thank you!
