### ISSUE TITLE
Dependency on railties (~> 3.0)

### ISSUE THREAD

**Issue by seifsallam** [colinyoung/cancan_strong_parameters#8]
I just migrated to Rails 4, and tried to install cancan_strong_parameters, but it depends on railties 3.0. Can you update the gem to support railties 4.0.0?

**Comment by colinyoung** [comment]
It doesn't actually depend on railties directly -- it's one of the child gems that does, namely strong_parameters. Since that's pretty critical to the gem, it's tough to fix quickly...

**Comment by colinyoung** [comment]
`strong_parameters` is now part of the Rails core for Rails 4. Therefore a solution would be to remove strong_parameters from the Gemspec, but you can see why that might be a bad idea for Rails 3 users... I'll think about a rails4 branch. What do you think?

**Comment by seifsallam** [comment]
A Rails 4 branch would work, but I'm guessing that most people come here because they migrated to rails 4 :) So I would go with removing the dependence while having a note saying for Rails 3 users, download v0.2 version

**Comment by elthariel** [comment]
but I'm guessing that most people come here because they migrated to rails 4 :)  -> true for me :)

**Comment by colinyoung** [comment]
Closed in v0.4! Thanks for your help, both of you!
